- src/functionalTest/java/uk/gov/hmcts/reform/wataskmonitor/MonitorTaskJobControllerForAdHocCreateTasksTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/wataskmonitor/MonitorTaskJobControllerForAdHocDeleteProcessInstanceTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/wataskmonitor/MonitorTaskJobControllerForConfigurationJobTest.java
> revert change

- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/GenericJobOutcome.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/GenericJobReport.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/configuration/ConfigurationJob.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/configuration/ConfigurationJobService.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/GenericJobOutcomeTest.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/GenericJobReportTest.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/configuration/ConfigurationJobTest.java
Added logging for configuration job
```
[ ] Yes
[x ] No
```
> Added logging

- src/main/resources/adhoc/update-case/ad-hoc-update-case-ccd-elastic-search-query.json
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/adhoc/createtasks/ElasticSearchCaseRetrieverServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-677
> adjust ES query to discard cases in ended and appealTakenOffline states

- Jenkinsfile_nightly
- build.gradle
https://tools.hmcts.net/jira/browse/RWA-626
```
[ ] Yes
[x ] No
```
> Added FTs to nightly build

- build.gradle
> Resolved wiremock dependency issue

- Jenkinsfile_nightly
> Ft nightly build fix

- build.gradle
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/domain/camunda/HistoryCamundaTaskTest.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/domain/idam/UserIdamTokenGeneratorInfoTest.java
> Added pitest task

- src/test/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/GenericJobOutcomeTest.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/adhoc/ElasticSearchRetrieverParameterTest.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/adhoc/createtasks/CreateTaskJobOutcomeTest.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/adhoc/createtasks/CreateTaskJobReportTest.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/adhoc/updatecasedata/UpdateCaseJobOutcomeTest.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/domain/taskmanagment/request/TerminateTaskRequestTest.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/domain/taskmanagment/request/options/TerminateInfoTest.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/domain/taskmonitor/request/JobDetailsTest.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/domain/taskmonitor/request/MonitorTaskJobRequestTest.java
> mutation test coverage

- Jenkinsfile_nightly
> Disabled mutation and security scan

- charts/wa-task-monitor/Chart.yaml
- charts/wa-task-monitor/values.yaml
- src/main/resources/application.yaml
Add task manaagement url
```
[ ] Yes
[x ] No
```
> Add task manaagement url

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RWA-775
updated Jenkins config to make demo branch in sync with master
```
[ ] Yes
[x] No
```
> RWA-775 updated jenkins config to make demo branch in sync with master

- src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/initiation/InitiationJobService.java
https://tools.hmcts.net/jira/browse/RWA-848
> improve logging for the initiation job

- src/integrationTest/java/uk/gov/hmcts/reform/wataskmonitor/controllers/MonitorTaskJobControllerForTerminationJobTest.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/taskmanagement/request/enums/TerminateReason.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/taskmanagement/request/options/TerminateInfo.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/initiation/InitiationJobService.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/termination/TerminationJobService.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/termination/TerminationJobServiceTest.java
Refactor termination calls to be generic
```
[ ] Yes
[x ] No
```
> RWA-951: Refactor termination calls to be generic

- src/testUtils/java/uk/gov/hmcts/reform/wataskmonitor/config/GivensBuilder.java
https://tools.hmcts.net/jira/browse/RWA-722
Remove group field
```
[ ] Yes
[ ] No
```
> feat:Remove group usage(RWA-722)

- Jenkinsfile_CNP
- src/functionalTest/java/uk/gov/hmcts/reform/wataskmonitor/MonitorTaskJobControllerForInitiationJobTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/wataskmonitor/SpringBootFunctionalBaseTest.java
- src/functionalTest/resources/application-functional.yaml
- src/integrationTest/java/uk/gov/hmcts/reform/wataskmonitor/controllers/MonitorTaskJobControllerForAdHocJobTest.java
- src/testUtils/java/uk/gov/hmcts/reform/wataskmonitor/config/DocumentManagementFiles.java
- src/testUtils/java/uk/gov/hmcts/reform/wataskmonitor/config/GivensBuilder.java
- src/testUtils/java/uk/gov/hmcts/reform/wataskmonitor/entities/TestAuthenticationCredentials.java
- src/testUtils/java/uk/gov/hmcts/reform/wataskmonitor/services/AuthorizationProvider.java
- src/testUtils/java/uk/gov/hmcts/reform/wataskmonitor/services/IdamServiceApi.java
- src/testUtils/java/uk/gov/hmcts/reform/wataskmonitor/utils/Common.java
Add idam account deletion through After annotation test lyfecycle
```
[ ] Yes
[x ] No
```
> RWA-974: Add idam account deletion through After annotation test lyfecycle

- charts/wa-task-monitor/Chart.yaml
Up the java chart version
```
[ ] Yes
[ ] No
```
> Refactor:Up the java chart version

- build.gradle
- config/owasp/suppressions.xml
refactor:resolve cve issue
```
[ ] Yes
[ ] No
```
> refactor:resolve cve issue

- Jenkinsfile_CNP
- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/RWA-950
```
[ ] Yes
[X] No
```
> mutation step added to nightly build

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1167
```
[ ] Yes
[X] No
```
> suppress CVE-2005-1036

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1254
```
[ ] Yes
[X] No
```
> RWA-1254 CVE-2020-36518 suppressed

- src/contractTest/resources/json/case_data_map.json
- src/functionalTest/resources/requests/ccd/case_data.json
https://tools.hmcts.net/jira/browse/RWA-1171
RWA-1171 add-waDummyPostcode
```
[ ] Yes
[X] No
```
> RWA-1171-add-waDummyPostcode

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1281
Suppress CVE-2022-22965 False positive
```
[ ] Yes
[X ] No
```
> RWA-1281 Suppress CVE-2022-22965 False Positive

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-1302
```
[ ] Yes
[ x] No
```
> RWA-1302: upgraded spring boot due to CVE-2022-22968

- charts/wa-task-monitor/Chart.yaml
- charts/wa-task-monitor/values.yaml
https://tools.hmcts.net/jira/browse/RWA-1098
Autoscaling for R1
```
[ ] Yes
[X] No
```
> RWA-1098-autoscaling for R1

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1407
supressed CVE-2016-1000027(not applicable to wa-task-monitor application, more information https://github.com/spring-projects/spring-framework/issues/24434#issuecomment-579669626)
fixed deprecation warnings from gradle
```
[ ] Yes
[x] No
```
> RWA-1407: CVE-2016-1000027 supression

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1428
Changes made according to [CVE-2022-22971](https://nvd.nist.gov/vuln/detail/CVE-2022-22971) and [CVE-2022-22970](https://nvd.nist.gov/vuln/detail/CVE-2022-22970)
```
[ ] Yes
[x] No
```
> RWA-1428 - CVE fixes

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1468
CVE-2022-22976 suppression
```
[ ] Yes
[x] No
```
> CVE-2022-22976 suppression

- src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/failure/initiation/TaskInitiationFailuresJobService.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/failure/termination/TaskTerminationFailuresJobService.java
https://tools.hmcts.net/jira/browse/RWA-1604
```
[ ] Yes
[X] No
```
> RWA-1604-initiation and termination failure message extended

- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/camunda/enums/CamundaVariableDefinition.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/taskmanagement/request/enums/TaskAttributeDefinition.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/initiation/InitiationTaskAttributesMapper.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/initiation/InitiationTaskAttributesMapperTest.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/initiation/helpers/InitiationHelpers.java
- src/testUtils/java/uk/gov/hmcts/reform/wataskmonitor/config/GivensBuilder.java
[RWA-1787](https://tools.hmcts.net/jira/browse/RWA-1787)
Cherry pick additional properties for initiation
```
[ ] Yes
[ ] No
```
> Cherry pick additional properties for initiation (RWA-1787)

- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/camunda/enums/CamundaVariableDefinition.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/taskmanagement/request/enums/TaskAttributeDefinition.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/initiation/InitiationTaskAttributesMapper.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/initiation/InitiationTaskAttributesMapperTest.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/initiation/helpers/InitiationHelpers.java
- src/testUtils/java/uk/gov/hmcts/reform/wataskmonitor/config/GivensBuilder.java
Reverts hmcts/wa-task-monitor#129
> Revert "Cherry pick additional properties for initiation (RWA-1787)"

- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/camunda/enums/CamundaVariableDefinition.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/taskmanagement/request/enums/TaskAttributeDefinition.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/initiation/InitiationTaskAttributesMapper.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/initiation/InitiationTaskAttributesMapperTest.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/initiation/helpers/InitiationHelpers.java
- src/testUtils/java/uk/gov/hmcts/reform/wataskmonitor/config/GivensBuilder.java
*
[RWA-1787](https://tools.hmcts.net/jira/browse/RWA-1787)
Cherry pick additional properties for initiation
```
[ ] Yes
[ ] No
```
> Cherry pick additional properties for initiation(RWA-1787)

- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/camunda/enums/CamundaVariableDefinition.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/initiation/InitiationTaskAttributesMapper.java
Filter priority date from camunda tasks for initiation
```
[ ] Yes
[ ] No
```
> Filter priority date from camunda tasks for initiation

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-1870
Suppression CVE fix - CVE-2022-42003
```
[ ] Yes
[x] No
```
> RWA-1870 - Suppression CVE fix - CVE-2022-42003

- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/taskmanagement/request/entities/TaskOperation.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/reconfiguration/ReconfigurationJobService.java
[RWA-1824](https://tools.hmcts.net/jira/browse/RWA-1824)
see ticket
```
[ ] Yes
[ X] No
```
> RWA-1824 Fix reconfiguration initiation issue

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-1861
gradle pitest plugin to 1.9.0
pitest junit5 to 1.1.0
pitest to 1.9.7
junit to 5.9.1
junit platfrom to 1.9.1
log4j-api / log4j-to-slf4j to 2.19.0
spring-security-test to 5.7.3
fortify-client to 1.2.2
document-management-client to 7.0.1
```
[ ] Yes
[x] No
```
> RWA-1861: Dependabot PRs merge

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-1971
-Fix the CVE for CVE-2022-31692, CVE-2022-31690, CVE-2022-42252
```
[ ] Yes
[X] No
```
> RWA-1971 Fix CVE-2022-31692, CVE-2022-31690, CVE-2022-42252

- src/functionalTest/java/uk/gov/hmcts/reform/wataskmonitor/MonitorTaskJobControllerForInitiationJobTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/wataskmonitor/SpringBootFunctionalBaseTest.java
[RWA-1882](https://tools.hmcts.net/jira/browse/RWA-1882)
Change description
Handle data conflict issue gracefully for duplicate task creation
```
[ ] Yes
[ ] No
```
> Handle inititation Duplicate error gracefully [RWA-1882]

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-1949
Like in the description
```
[ ] Yes
[X ] No
```
> RWA-1949 Output full jenkins logs

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- charts/wa-task-monitor/Chart.yaml
- charts/wa-task-monitor/values.yaml
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/taskmanagement/request/entities/TaskOperation.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/reconfiguration/ReconfigurationJobService.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/reconfiguration/ReconfigurationJobServiceTest.java
[RWA-1827](https://tools.hmcts.net/jira/browse/RWA-1827)
Add reconfiguration retry window time limit
```
[ ] Yes
[X ] No
```
> RWA-1827 Add reconfiguration retry window time limit

- charts/wa-task-monitor/Chart.yaml
Updating Chart Version
```
[ ] Yes
[x] No
```
> Updating Chart Version

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2090
RWA-2090 - suppression for CVE-2021-37533 until 31-12-2023
```
[ ] Yes
[x] No
```
> RWA-2090 - suppression for CVE-2021-37533 until 31-12-2023

- gradle/wrapper/gradle-wrapper.properties
RWA-2057 Gradle version Update to 7.6
```
[ ] Yes
[x] No
```
> RWA-2057 Gradle version Update to 7.6

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- README.md
- charts/wa-task-monitor/Chart.yaml
- charts/wa-task-monitor/values.yaml
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/wataskmonitor/SpringBootFunctionalBaseTest.java
- src/functionalTest/resources/application-functional.yaml
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/clients/TaskManagementClient.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/clients/TaskReconfigurationClient.java
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RWA-1955
```
[ ] Yes
[X] No
```
> RWA-1955-wa-task-management-api url standardized

- src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/reconfiguration/ReconfigurationJobService.java
https://tools.hmcts.net/jira/browse/RWA-1993
fixed reconfiguration request time issue
```
[ ] Yes
[ ] No
```
> RWA-1993 fixed reconfiguration request time issue

- charts/wa-task-monitor/Chart.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2329
```
[ ] Yes
[ x] No
```
> RWA-2329: suppress CVE-2022-45688

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2510
suppress CVE-2023-20863
```
[ ] Yes
[ x ] No
```
> RWA-2510: suppress CVE-2023-20863

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RWA-2349
Fix test reporting coverage
```
[ ] Yes
[ x] No
```
> RWA-2349 Fix test reporting coverage

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2444
suppress CVE-2023-35116
```
[ ] Yes
[ x ] No
```
> RWA-2444: suppress CVE-2023-35116

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2651
Suppress and/or fix CVEs
```
[ ] Yes
[ X ] No
```
> RWA-2651: suppress/fix CVEs

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-2690
Fix CVE-2023-34035
```
[ ] Yes
[ x ] No
```
> RWA-2690: fix CVE-2023-34035

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-2703
Fix CVE-2020-8908
```
[ ] Yes
[ x ] No
```
> RWA-2690: fix CVE-2020-8908

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2834
Extend suppression date for CVE-2023-35116
```
[ ] Yes
[x] No
```
> RWA-2834 Extend suppression date for CVE-2023-35116

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-2872
Upgrade tomcat to Fix New CVE's
```
[ ] Yes
[x] No
```
> RWA-2872 Upgraded Tomcat to fix new CVE's

- charts/wa-task-monitor/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-2845
Migrating to Workload Identity
```
[ ] Yes
[x] No
```
> RWA-2845 Migrating to Workload Identity

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2910
extend suppression for  CVE-2023-35116
```
[ ] Yes
[x ] No
```
> RWA-2910: extend suppression for  CVE-2023-35116

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2976
RWA-2976: Suppress CVE-2023-35116
```
[ ] Yes
[x] No
```
> RWA-2976: Suppress CVE-2023-35116

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-2995
Upgrade spring-security-rsa to v.1.11, tomcat to v.9.0.83 and spring boot to v.2.7.18
```
[ ] Yes
[x] No
```
> RWA-2995: Fix CVE-2023-33202,  CVE-2023-34055, CVE-2023-46589

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-3004
Upgrade logback
```
[ ] Yes
[ x] No
```
> RWA-3004: Fix CVE-2023-6378

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-3012
Need to upgrade OWASP - wa-task-monitor
```
[ ] Yes
[x] No
```
> RWA-3012 Need to upgrade OWASP - wa-task-monitor

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-3053
Fixing mutation tests
```
[ ] Yes
[ x ] No
```
> RWA-3053: Fixing mutation tests

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3088
Address CVEs
```
[ ] Yes
[ x ] No
```
> RWA-3088: Address CVEs

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3149
```
[ ] Yes
[X] No
```
> RWA-3149: Extend Suppression

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3226
```
[ ] Yes
[X] No
```
> RWA-3226: Extend Suppression

- charts/wa-task-monitor/Chart.yaml
- charts/wa-task-monitor/values.yaml
https://tools.hmcts.net/jira/browse/RWA-3126
```
[ ] Yes
[ ] No
```
> RWA-3126: spotInstance config added

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3324
```
[ ] Yes
[x] No
```
> RWA-3324: Extend Suppression

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3388
```
[ ] Yes
[x] No
```
> RWA-3388: Extend Suppression for CVE-2023-35116

- .github/dependabot.yml
https://tools.hmcts.net/jira/browse/RWA-3462
```
[ ] Yes
[X] No
```
> RWA-3462: Remove Dependabot

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RWA-3497
```
[ ] Yes
[x] No
```
> RWA-3497: Remove Suppression

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-3659
```
[ ] Yes
[x] No
```
> RWA-3659: Upgrade dependencycheck to 10.0.2

- src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/cleanup/MaintenanceCamundaTaskCleanUpJobServiceTest.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/cleanupsensitivelogs/CleanupSensitiveLogsJobServiceTest.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/cleanupsensitivelogs/CleanupSensitiveLogsJobTest.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/failure/initiation/TaskInitiationFailuresJobServiceTest.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/failure/termination/TaskTerminationFailuresJobServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-3728
RWA-3728 - Refactor CapturedOutput implementation for verifying logging
```
[ ] Yes
[x] No
```
> RWA-3728 - Refactor CapturedOutput implementation for verifying logging

- build.gradle
nightly-dev
Review failing mutation post renovate gradle upgrade
```
[ ] Yes
[x] No
```
> Review failing mutation post renovate gradle upgrade

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-3916
> Adding app insights dependencies

- .github/renovate.json
https://tools.hmcts.net/jira/browse/RWA-4056
Update renovate config
```
[ ] Yes
[x] No
```
> RWA-4056 update renovate config

- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/CaseIdList.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/GenericJobOutcome.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/GenericJobReport.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/JobOutcome.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/JobReport.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/RetrieveCaseListParam.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/adhoc/ElasticSearchRetrieverParameter.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/adhoc/createtasks/CreateTaskJobOutcome.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/adhoc/createtasks/CreateTaskJobReport.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/adhoc/createtasks/ElasticSearchCaseList.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/adhoc/createtasks/JsonResourceCaseList.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/adhoc/updatecasedata/UpdateCaseJobOutcome.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/domain/jobs/adhoc/updatecasedata/UpdateCaseJobReport.java
- src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/failure/termination/TaskTerminationFailuresJobService.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/failure/initiation/TaskInitiationFailuresJobServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-3888
Fixing codesmells highlighted by sonarqube
refactoring empty classes into interfaces
```
[ ] Yes
[x] No
```
> Code smells fixed, first class refactored into interface

- charts/wa-task-monitor/Chart.yaml
https://tools.hmcts.net/jira/browse/RWA-4202
Upgrading to oci charts
bumping java chart to latest version
```
[ ] Yes
[x] No
```
> RWA-4202: upgrading to oci chart

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-3997
```
[ ] Yes
[ ] No
```
> RWA-3997: Pact version upgrade

- src/main/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/failure/initiation/TaskInitiationFailuresJobService.java
- src/test/java/uk/gov/hmcts/reform/wataskmonitor/services/jobs/failure/initiation/TaskInitiationFailuresJobServiceTest.java
https://tools.hmcts.net/jira/browse/RWA-4153
Enrich warning message with the following data
caseId,
jurisdiction,
name,
caseType
```
[ ] Yes
[X] No
```
> Add more information to warning log message

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- docker-pactbroker-compose.yml
https://tools.hmcts.net/jira/browse/RWA-3463
Testing enable fortify scan in PR after being disabled for 3yrs.
Resolved fortify issues
Enabled fortify scan in nightly
```
[ ] Yes
[x] No
```
> RWA-3463: Enable fortify, resolve fortify password issue

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/RWA-4233
Removing test config from PR, fortify should only run in nightly.
```
[ ] Yes
[x] No
```
> RWA-3463: removing fortify from PR

- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/RWA-4261
```
[x] Yes
[ ] No
```
> RWA-4261 resolve afterSuccess

- README.md
https://tools.hmcts.net/jira/browse/RWA-3571
```
[ ] Yes
[ ] No
```
> RWA-3571: Readme Review

- CODEOWNERS
https://tools.hmcts.net/jira/browse/RWA-4241
Added WA team as codeowners
```
[ ] Yes
[x] No
```
> RWA-4241: Added codeowners

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-4371
> RWA-4371 - Update consumer version

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-4374
Bumped fortify-client version
set classifier to all 
```
[ ] Yes
[x] No
```
> RWA-4374: Bumped fortify-client, set classifier

- SECURITY.md
https://tools.hmcts.net/jira/browse/RWA-4240
```
[ ] Yes
[x] No
```
> RWA-4240: Added Security.md file

- build.gradle
https://tools.hmcts.net/jira/browse/RWA-4297
Update task monitor libraries
```
[ ] Yes
[x] No
```
> task monitor library upgrades

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- charts/wa-task-monitor/values.yaml
- src/functionalTest/resources/application-functional.yaml
- src/main/resources/application.yaml
- src/testUtils/java/uk/gov/hmcts/reform/wataskmonitor/services/AuthorizationProvider.java
https://tools.hmcts.net/jira/browse/RWA-4238
Removed hardcoded password from test user
```
[ ] Yes
[x] No
```
> RWA-4238: removed hardcoded password

- build.gradle
- src/contractTest/java/uk/gov/hmcts/reform/wataskmonitor/consumer/ccd/StartEventForCaseWorkerConsumerTest.java
- src/contractTest/java/uk/gov/hmcts/reform/wataskmonitor/consumer/ccd/StartForCaseWorkerConsumerTest.java
- src/contractTest/java/uk/gov/hmcts/reform/wataskmonitor/consumer/ccd/SubmitEventForCaseWorkerConsumerTest.java
- src/contractTest/java/uk/gov/hmcts/reform/wataskmonitor/consumer/ccd/SubmitForCaseWorkerConsumerTest.java
- src/contractTest/java/uk/gov/hmcts/reform/wataskmonitor/consumer/ccd/util/PactDslBuilderForCaseDetailsList.java
- src/contractTest/java/uk/gov/hmcts/reform/wataskmonitor/consumer/idam/IdamConsumerTestForPostToken.java
- src/contractTest/java/uk/gov/hmcts/reform/wataskmonitor/consumer/idam/IdamConsumerTestForPostUserInfo.java
https://tools.hmcts.net/jira/browse/RWA-4333
updated dependencies
```
[ ] Yes
[x] No
```
> RWA-4333 task monitor library upgrades
